#!/usr/bin/env python3
"""
Static Ad Generator — Phase 3: Image Generation via Google AI Studio (Nano Banana 2)

Lives permanently at skills/references/generate_ads.py.
Run it from anywhere — pass --brand to point at any brand folder under brands/.

Requirements:
    pip install google-genai Pillow

Usage:
    python skills/references/generate_ads.py --brand lmnt
    python skills/references/generate_ads.py --brand lmnt --templates 1,7,13,15
    python skills/references/generate_ads.py --brand lmnt --resolution 1K --variations 2
    python skills/references/generate_ads.py --brand lmnt --dry-run

Folder layout expected:
    brands/{brand}/
    ├── prompts.json          ← generated by Phase 2
    ├── product-images/       ← drop PNGs/JPGs here before running
    └── outputs/              ← generated images saved here (auto-created)

Environment:
    GOOGLE_API_KEY  — Google AI Studio key (https://aistudio.google.com/apikey)
                      Or place it in env/.env.local as GOOGLE_API_KEY=your-key
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path

try:
    from google import genai
    from google.genai import types
except ImportError:
    print("Error: 'google-genai' package required.  pip install google-genai")
    sys.exit(1)

try:
    from PIL import Image
except ImportError:
    print("Error: 'Pillow' package required.  pip install Pillow")
    sys.exit(1)

# ──────────────────────────────────────────────────────────────────────────────
# Paths — project root is three levels above this file
# skills/references/generate_ads.py  →  ../../..  →  project root
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR   = Path(__file__).resolve().parent          # skills/references/
PROJECT_ROOT = SCRIPT_DIR.parent.parent                  # static-ad-generator/
BRANDS_ROOT  = PROJECT_ROOT / "brands"
ENV_FILE     = PROJECT_ROOT / "env" / ".env.local"

# ──────────────────────────────────────────────────────────────────────────────
# Config
# ──────────────────────────────────────────────────────────────────────────────

MODEL              = "gemini-3.1-flash-image-preview"
DEFAULT_RESOLUTION = "2K"    # 512 | 1K | 2K | 4K
DEFAULT_VARIATIONS = 4       # images per template
MAX_REF_IMAGES     = 10      # Gemini hard limit for reference images per call
RATE_LIMIT_PAUSE   = 1       # seconds between variations (free-tier safety)

# ──────────────────────────────────────────────────────────────────────────────
# Template name map — kept in sync with template-prompts.md
# ──────────────────────────────────────────────────────────────────────────────

TEMPLATE_NAMES = {
    1:  "headline",
    2:  "offer-promotion",
    3:  "testimonials",
    4:  "features-benefits",
    5:  "bullet-points",
    6:  "social-proof",
    7:  "us-vs-them",
    8:  "before-after-ugc",
    9:  "negative-marketing",
    10: "press-editorial",
    11: "pull-quote-review",
    12: "lifestyle-colorway",
    13: "stat-surround-hero",
    14: "bundle-showcase",
    15: "social-comment-screenshot",
    16: "curiosity-gap-testimonial",
    17: "verified-review-card",
    18: "stat-surround-flatlay",
    19: "highlighted-testimonial",
    20: "advertorial-editorial",
    21: "bold-statement",
    22: "flavor-story",
    23: "long-form-manifesto",
    24: "product-comment-callout",
    25: "us-vs-them-color-split",
    26: "benefit-checklist",
    27: "stat-callout-lifestyle",
    28: "feature-arrow-callout",
    29: "ugc-viral-post",
    30: "hero-statement-icon-bar",
    31: "comparison-grid",
    32: "ugc-story-callout",
    33: "faux-press-screenshot",
    34: "faux-iphone-notes",
    35: "hero-product-stat-bar",
    36: "whiteboard-before-after",
    37: "hero-statement-promo",
    38: "ugc-lifestyle-review-split",
    39: "curiosity-gap-scroll-stopper",
    40: "post-it-note-style",
}

# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def load_api_key() -> str:
    """Read GOOGLE_API_KEY from environment or env/.env.local."""
    key = os.environ.get("GOOGLE_API_KEY", "").strip()
    if key:
        return key
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("GOOGLE_API_KEY="):
                key = line.split("=", 1)[1].strip().strip('"').strip("'")
                if key:
                    return key
    return ""


def list_brands() -> list[str]:
    """Return brand names that have a prompts.json ready."""
    if not BRANDS_ROOT.exists():
        return []
    return sorted(
        d.name for d in BRANDS_ROOT.iterdir()
        if d.is_dir() and (d / "prompts.json").exists()
    )


def load_product_images(product_images_dir: Path) -> list[tuple[str, Image.Image]]:
    """Load product-images/ folder as (filename, PIL.Image) pairs."""
    images = []
    for ext in ("*.png", "*.jpg", "*.jpeg", "*.webp"):
        for path in sorted(product_images_dir.glob(ext)):
            try:
                img = Image.open(path).convert("RGB")
                images.append((path.name, img))
                print(f"    + {path.name}")
            except Exception as exc:
                print(f"    ! Could not load {path.name}: {exc}")
    return images


def call_api(
    client: genai.Client,
    prompt: str,
    aspect_ratio: str,
    resolution: str,
    ref_images: list[tuple[str, Image.Image]],
) -> bytes | None:
    """
    Send prompt (+ optional reference images) to Nano Banana 2.
    Returns raw PNG bytes or None on failure.
    """
    pil_images = [img for _, img in ref_images[:MAX_REF_IMAGES]]
    contents   = [prompt] + pil_images

    response = client.models.generate_content(
        model=MODEL,
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["TEXT", "IMAGE"],
            image_config=types.ImageConfig(
                aspect_ratio=aspect_ratio,
                image_size=resolution,
            ),
        ),
    )

    for part in response.candidates[0].content.parts:
        if part.inline_data:
            return part.inline_data.data
    return None


def build_gallery(brand_dir: Path, brand_name: str, results: list[dict]) -> None:
    """Write outputs/index.html with a visual grid of every generated ad."""
    rows = ""
    for r in results:
        if not r["saved"]:
            continue
        rows += f"<h2>{r['num']:02d} — {r['name']}</h2>\n<div class='row'>\n"
        for p in r["saved"]:
            rel = Path(p).relative_to(brand_dir / "outputs")
            rows += (
                f"  <figure>"
                f"<img src='{rel}' loading='lazy'>"
                f"<figcaption>{Path(p).name}</figcaption>"
                f"</figure>\n"
            )
        rows += "</div>\n"

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{brand_name} — Static Ad Gallery</title>
<style>
  body       {{ font-family: sans-serif; background: #111; color: #eee; padding: 1rem 2rem; margin: 0; }}
  h1         {{ border-bottom: 2px solid #333; padding-bottom: .5rem; }}
  h1 span    {{ font-size: .65em; font-weight: 400; color: #666; }}
  h2         {{ margin: 2rem 0 .4rem; color: #888; font-size: .85rem; text-transform: uppercase; letter-spacing: .07em; }}
  .row       {{ display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: .5rem; }}
  figure     {{ margin: 0; }}
  img        {{ max-height: 260px; border-radius: 6px; display: block; cursor: zoom-in; }}
  figcaption {{ font-size: .65rem; color: #555; margin-top: 3px; }}
</style>
</head>
<body>
<h1>{brand_name} — Static Ads <span>generated {generated_at}</span></h1>
{rows}
</body>
</html>"""

    gallery_path = brand_dir / "outputs" / "index.html"
    gallery_path.parent.mkdir(parents=True, exist_ok=True)
    gallery_path.write_text(html, encoding="utf-8")
    print(f"\n  Gallery -> {gallery_path}")


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def main() -> None:
    available = list_brands()

    parser = argparse.ArgumentParser(
        description="Generate static ads with Nano Banana 2 (Google AI Studio)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python skills/references/generate_ads.py --brand lmnt\n"
            "  python skills/references/generate_ads.py --brand lmnt --templates 1,7,13\n"
            "  python skills/references/generate_ads.py --brand lmnt --resolution 1K --variations 2\n"
            "  python skills/references/generate_ads.py --brand lmnt --dry-run\n"
        ),
    )
    parser.add_argument(
        "--brand",
        required=True,
        metavar="NAME",
        help=(
            f"Brand folder name under brands/  "
            f"(available: {', '.join(available) if available else 'none yet'})"
        ),
    )
    parser.add_argument(
        "--templates",
        metavar="1,7,13",
        help="Comma-separated template numbers to run (default: all)",
    )
    parser.add_argument(
        "--resolution",
        default=DEFAULT_RESOLUTION,
        choices=["512", "1K", "2K", "4K"],
        help=f"Image resolution (default: {DEFAULT_RESOLUTION})",
    )
    parser.add_argument(
        "--variations",
        type=int,
        default=DEFAULT_VARIATIONS,
        metavar="N",
        help=f"Variations per template (default: {DEFAULT_VARIATIONS})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would run — no API calls made",
    )
    args = parser.parse_args()

    # ── Resolve brand dir ─────────────────────────────────────────────────────
    brand_dir = BRANDS_ROOT / args.brand
    if not brand_dir.exists():
        sys.exit(
            f"ERROR: brands/{args.brand}/ not found.\n"
            f"  Available: {', '.join(available) or 'none'}\n"
            f"  Expected path: {brand_dir}"
        )

    prompts_file = brand_dir / "prompts.json"
    if not prompts_file.exists():
        sys.exit(
            f"ERROR: prompts.json not found in brands/{args.brand}/\n"
            "  Run Phase 2 first to generate it."
        )

    # ── API key ───────────────────────────────────────────────────────────────
    api_key = load_api_key()
    if not api_key and not args.dry_run:
        sys.exit(
            "ERROR: GOOGLE_API_KEY not set.\n"
            "  Option 1: set env var  →  export GOOGLE_API_KEY='your-key'\n"
            f"  Option 2: add to      →  {ENV_FILE}\n"
            "  Get your key at: https://aistudio.google.com/apikey"
        )

    # ── Load prompts ──────────────────────────────────────────────────────────
    data        = json.loads(prompts_file.read_text(encoding="utf-8"))
    all_prompts = data["prompts"]
    brand_name  = data.get("brand", args.brand)
    product     = data.get("product", "")

    if args.templates:
        requested   = {int(t.strip()) for t in args.templates.split(",")}
        all_prompts = [p for p in all_prompts if p["template_number"] in requested]
        if not all_prompts:
            sys.exit(f"ERROR: No prompts matched template numbers: {args.templates}")

    # ── Load reference images ─────────────────────────────────────────────────
    img_dir     = brand_dir / "product-images"
    ref_images  = []
    if img_dir.exists():
        print(f"\nLoading product images from brands/{args.brand}/product-images/")
        ref_images = load_product_images(img_dir)
    else:
        print(f"\nNo product-images/ folder -- all templates will run text-only.")

    # ── Print run summary ─────────────────────────────────────────────────────
    total = len(all_prompts) * args.variations
    sep = "=" * 54
    print(f"\n{sep}")
    print(f"  Brand    : {brand_name}" + (f"  /  {product}" if product else ""))
    print(f"  Model    : {MODEL}")
    print(f"  Templates: {len(all_prompts)}  x  {args.variations} variation(s)  =  {total} images")
    print(f"  Refs     : {len(ref_images)} product image(s) loaded")
    print(f"  Res      : {args.resolution}  |  Output: brands/{args.brand}/outputs/")
    if args.dry_run:
        print(f"  Mode     : DRY RUN -- no API calls")
    print(f"{sep}\n")

    if args.dry_run:
        for p in all_prompts:
            num    = p["template_number"]
            name   = TEMPLATE_NAMES.get(num, p.get("template_name", f"template-{num}"))
            needs  = p.get("needs_product_images", False)
            aspect = p.get("aspect_ratio", "4:5")
            mode   = f"+ {len(ref_images)} ref(s)" if (needs and ref_images) else "text-only"
            print(f"  [{num:02d}] {name:<35} {aspect}  {mode}")
        print()
        return

    # ── Init Gemini client ────────────────────────────────────────────────────
    client = genai.Client(api_key=api_key)

    # ── Generate ──────────────────────────────────────────────────────────────
    completed = 0
    failed    = 0
    results   = []

    for prompt_obj in all_prompts:
        num         = prompt_obj["template_number"]
        name        = TEMPLATE_NAMES.get(num, prompt_obj.get("template_name", f"template-{num}"))
        prompt_text = prompt_obj["prompt"]
        aspect      = prompt_obj.get("aspect_ratio", "4:5")
        needs_ref   = prompt_obj.get("needs_product_images", False)

        refs  = ref_images if (needs_ref and ref_images) else []
        mode  = f"+ {len(refs)} ref(s)" if refs else "text-only"

        out_dir = brand_dir / "outputs" / f"{num:02d}-{name}"
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "prompt.txt").write_text(prompt_text, encoding="utf-8")

        print(f"[{num:02d}] {name}  ({aspect}, {mode})")

        saved = []

        for v in range(1, args.variations + 1):
            print(f"  -> v{v}/{args.variations} ...", end=" ", flush=True)
            try:
                img_bytes = call_api(client, prompt_text, aspect, args.resolution, refs)

                if not img_bytes:
                    print("FAIL  no image in response")
                    failed += 1
                    continue

                filename  = f"{name}_v{v}.png"
                save_path = out_dir / filename
                save_path.write_bytes(img_bytes)
                saved.append(str(save_path))
                print(f"OK  {filename}")
                completed += 1

            except Exception as exc:
                print(f"FAIL  {exc}")
                failed += 1

            if v < args.variations:
                time.sleep(RATE_LIMIT_PAUSE)

        results.append({"num": num, "name": name, "saved": saved})

    # ── Gallery + final summary ───────────────────────────────────────────────
    build_gallery(brand_dir, brand_name, results)

    sep2 = "-" * 54
    print(f"\n{sep2}")
    print(f"  Done.  OK {completed} saved   FAIL {failed}   total {completed + failed}")
    print(f"{sep2}\n")


if __name__ == "__main__":
    main()
