#!/usr/bin/env python3
"""
Static Ad Generator — Phase 3: Image Generation via Google AI Studio (Nano Banana 2)

Lives permanently at skills/references/generate_ads.py.
Run it from anywhere — pass --brand and --type to point at any brand folder under brands/.

Requirements:
    pip install google-genai Pillow

Usage (product brands):
    python skills/references/generate_ads.py --brand lmnt --type product
    python skills/references/generate_ads.py --brand lmnt --type product --templates 1,7,13,15
    python skills/references/generate_ads.py --brand lmnt --type product --dry-run

Usage (service/SaaS brands):
    python skills/references/generate_ads.py --brand notion --type service
    python skills/references/generate_ads.py --brand notion --type service --templates 1,4,13
    python skills/references/generate_ads.py --brand notion --type service --recommend
    python skills/references/generate_ads.py --brand notion --type service --dry-run

Folder layout expected:
    brands/{brand}/
    ├── prompts.json          ← generated by Phase 2
    ├── product-images/       ← (product) drop PNGs/JPGs here before running
    ├── brand-assets/         ← (service) categorized subfolders:
    │   ├── screenshots/      │   App/dashboard screenshots, UI screens
    │   ├── team/             │   Team photos, founder headshots
    │   ├── logos/            │   Brand logo, integration partner logos
    │   └── icons/            │   App icons, feature icons, illustrations
    └── outputs/              ← generated images saved here (auto-created)

Environment:
    GOOGLE_API_KEY       — Google AI Studio key (when PUBLIC_VERSION=false)
    OPENROUTER_API_KEY   — OpenRouter API key (when PUBLIC_VERSION=true)
    PUBLIC_VERSION       — "true" uses OpenRouter (Nemotron + Grok Imagine); "false" uses Gemini
"""

import argparse
import json
import sys
import time
from datetime import datetime
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: 'Pillow' package required.  pip install Pillow")
    sys.exit(1)

from config import ENV_FILE, emit_progress, get_image_model_name, get_public_image_latency_seconds, get_rate_limit_pause, get_resolution_choices, is_public_version, missing_image_api_key
from image_provider import MAX_REF_IMAGES, generate_image

# ──────────────────────────────────────────────────────────────────────────────
# Paths — project root is three levels above this file
# skills/references/generate_ads.py  →  ../../..  →  project root
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR   = Path(__file__).resolve().parent          # skills/references/
PROJECT_ROOT = SCRIPT_DIR.parent.parent                  # static-ad-generator/
BRANDS_ROOT  = PROJECT_ROOT / "brands"
ENV_FILE     = PROJECT_ROOT / "env" / ".env.local"

# ──────────────────────────────────────────────────────────────────────────────
# Config
# ──────────────────────────────────────────────────────────────────────────────

MODEL              = get_image_model_name()
DEFAULT_RESOLUTION = "512"   # provider-specific choices via get_resolution_choices()
DEFAULT_VARIATIONS = 2       # images per template
RATE_LIMIT_PAUSE   = get_rate_limit_pause()

# ──────────────────────────────────────────────────────────────────────────────
# Template name maps — kept in sync with template-prompts.md / service-template-prompts.md
# ──────────────────────────────────────────────────────────────────────────────

TEMPLATE_NAMES = {
    1:  "headline",
    2:  "offer-promotion",
    3:  "testimonials",
    4:  "features-benefits",
    5:  "bullet-points",
    6:  "social-proof",
    7:  "us-vs-them",
    8:  "before-after-ugc",
    9:  "negative-marketing",
    10: "press-editorial",
    11: "pull-quote-review",
    12: "lifestyle-colorway",
    13: "stat-surround-hero",
    14: "bundle-showcase",
    15: "social-comment-screenshot",
    16: "curiosity-gap-testimonial",
    17: "verified-review-card",
    18: "stat-surround-flatlay",
    19: "highlighted-testimonial",
    20: "advertorial-editorial",
    21: "bold-statement",
    22: "flavor-story",
    23: "long-form-manifesto",
    24: "product-comment-callout",
    25: "us-vs-them-color-split",
    26: "benefit-checklist",
    27: "stat-callout-lifestyle",
    28: "feature-arrow-callout",
    29: "ugc-viral-post",
    30: "hero-statement-icon-bar",
    31: "comparison-grid",
    32: "ugc-story-callout",
    33: "faux-press-screenshot",
    34: "faux-iphone-notes",
    35: "hero-product-stat-bar",
    36: "whiteboard-before-after",
    37: "hero-statement-promo",
    38: "ugc-lifestyle-review-split",
    39: "curiosity-gap-scroll-stopper",
    40: "post-it-note-style",
}

SERVICE_TEMPLATE_NAMES = {
    1:  "headline-ui-hero",
    2:  "pricing-tier-offer",
    3:  "testimonials",
    4:  "features-benefits",
    5:  "bullet-points",
    6:  "social-proof",
    7:  "us-vs-them-features",
    8:  "workflow-before-after",
    9:  "negative-marketing",
    10: "press-editorial",
    11: "pull-quote-review",
    12: "integration-ecosystem",
    13: "stat-surround-ui-hero",
    14: "plan-tier-showcase",
    15: "social-comment-screenshot",
    16: "curiosity-gap-testimonial",
    17: "verified-review-card",
    18: "stat-surround-workspace",
    19: "highlighted-testimonial",
    20: "advertorial-editorial",
    21: "bold-statement",
    22: "roi-calculator-visual",
    23: "long-form-manifesto",
    24: "app-comment-callout",
    25: "us-vs-them-feature-split",
    26: "stat-callout-lifestyle",
    27: "benefit-checklist",
    28: "feature-arrow-callout",
    29: "ugc-viral-post",
    30: "hero-statement-icon-bar",
    31: "comparison-grid-features",
    32: "ugc-story-callout",
    33: "faux-press-screenshot",
    34: "faux-iphone-notes",
    35: "hero-ui-stat-bar",
    36: "onboarding-steps",
    37: "hero-statement-promo",
    38: "demo-cta",
    39: "curiosity-gap-scroll-stopper",
    40: "post-it-note-style",
}

# Asset categories for service brand-assets/ subfolders
ASSET_CATEGORIES = ("screenshots", "team", "logos", "icons")
IMAGE_EXTENSIONS = ("*.png", "*.jpg", "*.jpeg", "*.webp")

# Static asset requirements per service template (mirrors service-template-prompts.md)
# Used by --recommend when prompts.json doesn't exist yet (pre-Phase 2).
SERVICE_TEMPLATE_ASSETS: dict[int, dict[str, list[str]]] = {
    1:  {"required": ["screenshots"], "preferred": []},
    2:  {"required": ["screenshots"], "preferred": ["logos"]},
    3:  {"required": ["screenshots"], "preferred": ["team"]},
    4:  {"required": ["screenshots"], "preferred": ["icons"]},
    5:  {"required": ["screenshots"], "preferred": []},
    6:  {"required": ["screenshots", "logos"], "preferred": []},
    7:  {"required": ["screenshots"], "preferred": ["logos"]},
    8:  {"required": ["screenshots"], "preferred": ["icons"]},
    9:  {"required": ["screenshots"], "preferred": []},
    10: {"required": ["screenshots", "logos"], "preferred": ["team"]},
    11: {"required": ["screenshots"], "preferred": []},
    12: {"required": ["logos", "screenshots"], "preferred": ["icons"]},
    13: {"required": ["screenshots"], "preferred": ["icons"]},
    14: {"required": ["screenshots"], "preferred": ["icons"]},
    15: {"required": ["screenshots"], "preferred": []},
    16: {"required": ["screenshots"], "preferred": []},
    17: {"required": ["screenshots"], "preferred": []},
    18: {"required": ["screenshots"], "preferred": ["team"]},
    19: {"required": ["screenshots"], "preferred": ["team"]},
    20: {"required": [], "preferred": ["team"]},
    21: {"required": ["screenshots"], "preferred": []},
    22: {"required": ["screenshots"], "preferred": ["icons"]},
    23: {"required": ["screenshots"], "preferred": []},
    24: {"required": ["screenshots"], "preferred": []},
    25: {"required": ["screenshots"], "preferred": ["logos"]},
    26: {"required": ["screenshots"], "preferred": ["team"]},
    27: {"required": ["screenshots"], "preferred": ["icons"]},
    28: {"required": ["screenshots"], "preferred": ["icons"]},
    29: {"required": [], "preferred": []},
    30: {"required": ["screenshots"], "preferred": ["icons"]},
    31: {"required": ["screenshots"], "preferred": ["logos"]},
    32: {"required": ["screenshots"], "preferred": []},
    33: {"required": ["screenshots"], "preferred": ["team", "logos"]},
    34: {"required": ["screenshots"], "preferred": []},
    35: {"required": ["screenshots"], "preferred": []},
    36: {"required": ["screenshots"], "preferred": ["icons"]},
    37: {"required": ["screenshots"], "preferred": ["icons"]},
    38: {"required": ["screenshots"], "preferred": ["team", "icons"]},
    39: {"required": [], "preferred": []},
    40: {"required": ["screenshots"], "preferred": []},
}

# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def list_brands() -> list[str]:
    """Return brand names that have a prompts.json ready."""
    if not BRANDS_ROOT.exists():
        return []
    return sorted(
        d.name for d in BRANDS_ROOT.iterdir()
        if d.is_dir() and (d / "prompts.json").exists()
    )


def load_images_from_dir(image_dir: Path, label: str = "") -> list[tuple[str, Image.Image]]:
    """Load all images from a directory as (filename, PIL.Image) pairs."""
    images = []
    for ext in IMAGE_EXTENSIONS:
        for path in sorted(image_dir.glob(ext)):
            try:
                img = Image.open(path).convert("RGB")
                images.append((path.name, img))
                prefix = f"    [{label}] " if label else "    "
                print(f"{prefix}+ {path.name}")
            except Exception as exc:
                print(f"    ! Could not load {path.name}: {exc}")
    return images


def load_product_images(product_images_dir: Path) -> list[tuple[str, Image.Image]]:
    """Load product-images/ folder as (filename, PIL.Image) pairs. Product pipeline only."""
    return load_images_from_dir(product_images_dir)


# ──────────────────────────────────────────────────────────────────────────────
# Service asset scanning + recommendation helpers
# ──────────────────────────────────────────────────────────────────────────────

def scan_brand_assets(brand_dir: Path) -> dict[str, list[Path]]:
    """Scan brand-assets/ subfolders and return {category: [image_paths]}."""
    assets_dir = brand_dir / "brand-assets"
    scan: dict[str, list[Path]] = {cat: [] for cat in ASSET_CATEGORIES}
    if not assets_dir.exists():
        return scan
    for cat in ASSET_CATEGORIES:
        cat_dir = assets_dir / cat
        if cat_dir.is_dir():
            for ext in IMAGE_EXTENSIONS:
                scan[cat].extend(sorted(cat_dir.glob(ext)))
    return scan


def check_template_eligibility(
    prompts: list[dict],
    asset_scan: dict[str, list[Path]],
) -> list[dict]:
    """
    For each service template, determine eligibility based on available assets.
    Returns list of {num, name, status, missing_required, missing_preferred}.
    Status: 'ready' | 'partial' | 'blocked'
    """
    populated = {cat for cat, paths in asset_scan.items() if paths}
    results = []
    for p in prompts:
        num  = p["template_number"]
        name = p.get("template_name", SERVICE_TEMPLATE_NAMES.get(num, f"template-{num}"))
        required  = set(p.get("required_assets", []))
        preferred = set(p.get("preferred_assets", []))

        missing_req  = required - populated
        missing_pref = preferred - populated

        if missing_req:
            status = "blocked"
        elif missing_pref:
            status = "partial"
        else:
            status = "ready"

        results.append({
            "num": num,
            "name": name,
            "status": status,
            "missing_required": sorted(missing_req),
            "missing_preferred": sorted(missing_pref),
        })
    return results


def load_assets_for_template(
    template: dict,
    asset_scan: dict[str, list[Path]],
) -> list[tuple[str, Image.Image]]:
    """
    Load only the relevant subfolder images for a specific service template.
    Uses required_assets + preferred_assets to pick which categories to load.
    """
    categories = set(template.get("required_assets", []))
    categories |= set(template.get("preferred_assets", []))
    images: list[tuple[str, Image.Image]] = []
    for cat in sorted(categories):
        for path in asset_scan.get(cat, []):
            try:
                img = Image.open(path).convert("RGB")
                images.append((path.name, img))
            except Exception:
                pass
    return images


def print_recommend_report(
    eligibility: list[dict],
    asset_scan: dict[str, list[Path]],
) -> None:
    """Print a formatted --recommend report."""
    print("\n  Brand assets scan:")
    for cat in ASSET_CATEGORIES:
        count = len(asset_scan[cat])
        icon  = "✓" if count else "✗"
        label = f"{count} image(s)" if count else "empty"
        print(f"    {cat + '/':<16} {icon}  {label}")

    ready   = [e for e in eligibility if e["status"] == "ready"]
    partial = [e for e in eligibility if e["status"] == "partial"]
    blocked = [e for e in eligibility if e["status"] == "blocked"]
    total   = len(eligibility)

    print(f"\n  Template eligibility ({total} total):")
    if ready:
        nums = ", ".join(f"S{e['num']}" for e in ready)
        print(f"    ✓  READY   ({len(ready)}): {nums}")
    if partial:
        nums = ", ".join(f"S{e['num']}" for e in partial)
        cats = sorted({c for e in partial for c in e['missing_preferred']})
        print(f"    ⚠  PARTIAL ({len(partial)}): {nums} — would improve with: {', '.join(c + '/' for c in cats)}")
    if blocked:
        nums = ", ".join(f"S{e['num']}" for e in blocked)
        cats = sorted({c for e in blocked for c in e['missing_required']})
        print(f"    ✗  BLOCKED ({len(blocked)}): {nums} — missing required: {', '.join(c + '/' for c in cats)}")

    # Actionable recommendation
    all_missing = set()
    for e in blocked + partial:
        all_missing.update(e["missing_required"])
        all_missing.update(e["missing_preferred"])
    if all_missing:
        unlockable = len(blocked) + len(partial)
        print(f"\n  Recommendation: Add assets to {', '.join(c + '/' for c in sorted(all_missing))} "
              f"to unlock/improve {unlockable} more template(s).")
    else:
        print(f"\n  All {total} templates are fully eligible. Ready to generate.")
    print()


def call_api(
    prompt: str,
    aspect_ratio: str,
    resolution: str,
    ref_images: list[tuple[str, Image.Image]],
    *,
    seed: int | None = None,
) -> bytes | None:
    """Send prompt (+ optional reference images) to the active image provider."""
    return generate_image(
        prompt,
        aspect_ratio,
        resolution,
        ref_images,
        seed=seed,
    )


def build_gallery(brand_dir: Path, brand_name: str, results: list[dict]) -> None:
    """Write outputs/index.html with a visual grid of every generated ad."""
    rows = ""
    for r in results:
        if not r["saved"]:
            continue
        rows += f"<h2>{r['num']:02d} — {r['name']}</h2>\n<div class='row'>\n"
        for p in r["saved"]:
            rel = Path(p).relative_to(brand_dir / "outputs")
            rows += (
                f"  <figure>"
                f"<img src='{rel}' loading='lazy'>"
                f"<figcaption>{Path(p).name}</figcaption>"
                f"</figure>\n"
            )
        rows += "</div>\n"

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{brand_name} — Static Ad Gallery</title>
<style>
  body       {{ font-family: sans-serif; background: #111; color: #eee; padding: 1rem 2rem; margin: 0; }}
  h1         {{ border-bottom: 2px solid #333; padding-bottom: .5rem; }}
  h1 span    {{ font-size: .65em; font-weight: 400; color: #666; }}
  h2         {{ margin: 2rem 0 .4rem; color: #888; font-size: .85rem; text-transform: uppercase; letter-spacing: .07em; }}
  .row       {{ display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: .5rem; }}
  figure     {{ margin: 0; }}
  img        {{ max-height: 260px; border-radius: 6px; display: block; cursor: zoom-in; }}
  figcaption {{ font-size: .65rem; color: #555; margin-top: 3px; }}
</style>
</head>
<body>
<h1>{brand_name} — Static Ads <span>generated {generated_at}</span></h1>
{rows}
</body>
</html>"""

    gallery_path = brand_dir / "outputs" / "index.html"
    gallery_path.parent.mkdir(parents=True, exist_ok=True)
    gallery_path.write_text(html, encoding="utf-8")
    print(f"\n  Gallery -> {gallery_path}")


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def main() -> None:
    available = list_brands()

    parser = argparse.ArgumentParser(
        description="Generate static ads with the configured image provider",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples (product):\n"
            "  python skills/references/generate_ads.py --brand lmnt --type product\n"
            "  python skills/references/generate_ads.py --brand lmnt --type product --templates 1,7,13\n"
            "  python skills/references/generate_ads.py --brand lmnt --type product --dry-run\n"
            "\n"
            "Examples (service/SaaS):\n"
            "  python skills/references/generate_ads.py --brand notion --type service\n"
            "  python skills/references/generate_ads.py --brand notion --type service --recommend\n"
            "  python skills/references/generate_ads.py --brand notion --type service --dry-run\n"
        ),
    )
    parser.add_argument(
        "--brand",
        required=True,
        metavar="NAME",
        help=(
            f"Brand folder name under brands/  "
            f"(available: {', '.join(available) if available else 'none yet'})"
        ),
    )
    parser.add_argument(
        "--type",
        required=True,
        choices=["product", "service"],
        dest="brand_type",
        help="Brand type: 'product' (physical goods) or 'service' (SaaS/digital)",
    )
    parser.add_argument(
        "--templates",
        metavar="1,7,13",
        help="Comma-separated template numbers to run (default: all)",
    )
    parser.add_argument(
        "--resolution",
        default=DEFAULT_RESOLUTION,
        choices=list(get_resolution_choices()),
        help=f"Image resolution (default: {DEFAULT_RESOLUTION})",
    )
    parser.add_argument(
        "--variations",
        type=int,
        default=DEFAULT_VARIATIONS,
        metavar="N",
        help=f"Variations per template (default: {DEFAULT_VARIATIONS})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would run — no API calls made",
    )
    parser.add_argument(
        "--recommend",
        action="store_true",
        help="(service only) Scan brand-assets/ and report which templates are eligible",
    )
    args = parser.parse_args()

    # ── Select template map based on --type ───────────────────────────────────
    is_service   = args.brand_type == "service"
    template_map = SERVICE_TEMPLATE_NAMES if is_service else TEMPLATE_NAMES

    # ── Resolve brand dir ─────────────────────────────────────────────────────
    brand_dir = BRANDS_ROOT / args.brand
    if not brand_dir.exists():
        sys.exit(
            f"ERROR: brands/{args.brand}/ not found.\n"
            f"  Available: {', '.join(available) or 'none'}\n"
            f"  Expected path: {brand_dir}"
        )

    prompts_file = brand_dir / "prompts.json"
    # --recommend on a service brand works before Phase 2 (no prompts.json needed)
    recommend_no_prompts = args.recommend and is_service and not prompts_file.exists()
    if not prompts_file.exists() and not recommend_no_prompts:
        sys.exit(
            f"ERROR: prompts.json not found in brands/{args.brand}/\n"
            "  Run Phase 2 first to generate it.\n"
            "  Tip: you can still scan your assets now with --recommend."
        )

    # ── API key ───────────────────────────────────────────────────────────────
    missing = missing_image_api_key()
    if missing and not args.dry_run and not args.recommend:
        provider = "OpenRouter" if is_public_version() else "Google AI Studio"
        sys.exit(
            f"ERROR: {missing} not set.\n"
            f"  Add it to env/.env.local for {provider} image generation.\n"
            f"  File: {ENV_FILE}"
        )

    # ── Load prompts ──────────────────────────────────────────────────────────
    if recommend_no_prompts:
        # Build synthetic prompt list from static asset requirements
        all_prompts = [
            {
                "template_number": num,
                "template_name": SERVICE_TEMPLATE_NAMES.get(num, f"template-{num}"),
                "required_assets": SERVICE_TEMPLATE_ASSETS[num]["required"],
                "preferred_assets": SERVICE_TEMPLATE_ASSETS[num]["preferred"],
            }
            for num in sorted(SERVICE_TEMPLATE_ASSETS)
        ]
        brand_name = args.brand
        product    = ""
    else:
        data        = json.loads(prompts_file.read_text(encoding="utf-8"))
        all_prompts = data["prompts"]
        brand_name  = data.get("brand", args.brand)
        product     = data.get("product", "")

    if args.templates:
        requested   = {int(t.strip()) for t in args.templates.split(",")}
        all_prompts = [p for p in all_prompts if p["template_number"] in requested]
        if not all_prompts:
            sys.exit(f"ERROR: No prompts matched template numbers: {args.templates}")

    # ── Load reference images (branched by type) ──────────────────────────────
    ref_images   = []  # product: flat list used for all templates
    asset_scan   = {}  # service: per-category scan

    if is_service:
        asset_scan = scan_brand_assets(brand_dir)
        total_assets = sum(len(v) for v in asset_scan.values())
        if total_assets:
            print(f"\nScanning brand-assets/ for brands/{args.brand}/")
            for cat in ASSET_CATEGORIES:
                count = len(asset_scan[cat])
                if count:
                    print(f"    {cat + '/':<16} {count} image(s)")
        else:
            print(f"\nNo brand-assets/ subfolders populated -- templates will run text-only.")

        # ── --recommend mode (service only) ───────────────────────────────────
        if args.recommend:
            eligibility = check_template_eligibility(all_prompts, asset_scan)
            print_recommend_report(eligibility, asset_scan)
            return
    else:
        img_dir = brand_dir / "product-images"
        if img_dir.exists():
            print(f"\nLoading product images from brands/{args.brand}/product-images/")
            ref_images = load_product_images(img_dir)
        else:
            print(f"\nNo product-images/ folder -- all templates will run text-only.")

        if args.recommend:
            print("\n  --recommend is only available for --type service. Ignored.")

    # ── Print run summary ─────────────────────────────────────────────────────
    total = len(all_prompts) * args.variations
    sep = "=" * 54
    refs_label = (
        f"{sum(len(v) for v in asset_scan.values())} brand asset(s) across {sum(1 for v in asset_scan.values() if v)} categorie(s)"
        if is_service
        else f"{len(ref_images)} product image(s) loaded"
    )
    print(f"\n{sep}")
    print(f"  Brand    : {brand_name}" + (f"  /  {product}" if product else ""))
    print(f"  Type     : {args.brand_type}")
    print(f"  Model    : {MODEL}")
    if is_public_version():
        print(f"  Latency  : ~{get_public_image_latency_seconds()}s per image")
    print(f"  Templates: {len(all_prompts)}  x  {args.variations} variation(s)  =  {total} images")
    print(f"  Refs     : {refs_label}")
    print(f"  Res      : {args.resolution}  |  Output: brands/{args.brand}/outputs/")
    if args.dry_run:
        print(f"  Mode     : DRY RUN -- no API calls")
    print(f"{sep}\n")

    if args.dry_run:
        # For service dry-run, also show per-template eligibility
        eligibility_map = {}
        if is_service:
            for e in check_template_eligibility(all_prompts, asset_scan):
                eligibility_map[e["num"]] = e

        for p in all_prompts:
            num    = p["template_number"]
            name   = template_map.get(num, p.get("template_name", f"template-{num}"))
            aspect = p.get("aspect_ratio", "4:5")

            if is_service:
                # Per-template asset loading
                t_assets = load_assets_for_template(p, asset_scan)
                mode = f"+ {len(t_assets)} asset(s)" if t_assets else "text-only"
                elig = eligibility_map.get(num)
                if elig:
                    if elig["status"] == "ready":
                        status = "✓ READY"
                    elif elig["status"] == "partial":
                        status = f"⚠ better with {', '.join(c + '/' for c in elig['missing_preferred'])}"
                    else:
                        status = f"✗ BLOCKED (needs {', '.join(c + '/' for c in elig['missing_required'])})"
                    print(f"  [{num:02d}] {name:<35} {aspect}  {mode:<20} {status}")
                else:
                    print(f"  [{num:02d}] {name:<35} {aspect}  {mode}")
            else:
                needs = p.get("needs_product_images", False)
                mode  = f"+ {len(ref_images)} ref(s)" if (needs and ref_images) else "text-only"
                print(f"  [{num:02d}] {name:<35} {aspect}  {mode}")
        print()
        return

    # ── Generate ──────────────────────────────────────────────────────────────
    completed = 0
    failed    = 0
    results   = []
    total_images = len(all_prompts) * args.variations
    images_done = 0

    emit_progress(35, f"Generating {total_images} image(s)…", phase="phase3", totalImages=total_images)

    for prompt_obj in all_prompts:
        num         = prompt_obj["template_number"]
        name        = template_map.get(num, prompt_obj.get("template_name", f"template-{num}"))
        prompt_text = prompt_obj["prompt"]
        aspect      = prompt_obj.get("aspect_ratio", "4:5")

        if is_service:
            refs = load_assets_for_template(prompt_obj, asset_scan)
        else:
            needs_ref = prompt_obj.get("needs_product_images", False)
            refs = ref_images if (needs_ref and ref_images) else []

        mode  = f"+ {len(refs)} ref(s)" if refs else "text-only"

        out_dir = brand_dir / "outputs" / f"{num:02d}-{name}"
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "prompt.txt").write_text(prompt_text, encoding="utf-8")

        print(f"[{num:02d}] {name}  ({aspect}, {mode})")

        saved = []

        for v in range(1, args.variations + 1):
            images_done += 1
            pct = 35 + int((images_done / max(total_images, 1)) * 60)
            emit_progress(
                pct,
                f"Template {num} — variation {v}/{args.variations}",
                phase="phase3",
                template=num,
                variation=v,
                completedImages=images_done,
                totalImages=total_images,
            )
            print(f"  -> v{v}/{args.variations} ...", end=" ", flush=True)
            try:
                img_bytes = call_api(
                    prompt_text, aspect, args.resolution, refs, seed=v
                )

                if not img_bytes:
                    print("FAIL  no image in response")
                    failed += 1
                    continue

                filename  = f"{name}_v{v}.png"
                save_path = out_dir / filename
                save_path.write_bytes(img_bytes)
                saved.append(str(save_path))
                print(f"OK  {filename}")
                completed += 1

            except Exception as exc:
                print(f"FAIL  {exc}")
                failed += 1

            if v < args.variations:
                time.sleep(RATE_LIMIT_PAUSE)

        results.append({"num": num, "name": name, "saved": saved})

    # ── Gallery + final summary ───────────────────────────────────────────────
    emit_progress(95, "Building gallery…", phase="phase3")
    build_gallery(brand_dir, brand_name, results)

    sep2 = "-" * 54
    print(f"\n{sep2}")
    print(f"  Done.  OK {completed} saved   FAIL {failed}   total {completed + failed}")
    print(f"{sep2}\n")

    if failed > 0 and completed == 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
